import json
import os
import re
import subprocess
import urllib.request
from pathlib import Path

ALLOWED_REPO = os.getenv("ALLOWED_REPO", "DylanOSlab/market-data-reliability-lab")
NVIDIA_MODEL = os.getenv("NVIDIA_MODEL", "meta/llama-3.1-70b-instruct")
NVIDIA_URL = "https://integrate.api.nvidia.com/v1/chat/completions"

SYSTEM_PROMPT = """You are an autonomous maintenance agent for one disposable test repository.
Choose exactly one small, low-risk improvement. Prefer tests, documentation, validation,
error handling, or deterministic reliability fixes. Return ONLY valid JSON with keys:
summary, branch, commit_message, pr_title, pr_body, files. files is an array of objects
with path and content containing the complete replacement file. Never modify .github,
secrets, permissions, billing, repository settings, lock files, or binary files.
Do not delete files. Keep the change under 5 files and 500 changed lines.
"""

def sh(*args):
    return subprocess.check_output(args, text=True).strip()

def repo_context():
    allowed=[]
    for p in Path('.').rglob('*'):
        if not p.is_file() or '.git' in p.parts:
            continue
        if p.parts[0] == '.github' or p.suffix.lower() in {'.png','.jpg','.jpeg','.gif','.zip','.pdf'}:
            continue
        if p.stat().st_size > 40000:
            continue
        allowed.append(p)
    allowed=allowed[:80]
    chunks=[]
    for p in allowed:
        try:
            chunks.append(f"\n--- FILE: {p} ---\n{p.read_text(errors='replace')}")
        except Exception:
            pass
    return ''.join(chunks)[:120000]

def call_nim(prompt):
    key=os.environ['NVIDIA_API_KEY']
    body=json.dumps({
        'model': NVIDIA_MODEL,
        'messages':[{'role':'system','content':SYSTEM_PROMPT},{'role':'user','content':prompt}],
        'temperature':0.2,
        'max_tokens':6000,
        'stream':False
    }).encode()
    req=urllib.request.Request(NVIDIA_URL, data=body, method='POST', headers={
        'Authorization':f'Bearer {key}', 'Content-Type':'application/json', 'Accept':'application/json'})
    with urllib.request.urlopen(req, timeout=180) as r:
        data=json.load(r)
    text=data['choices'][0]['message']['content'].strip()
    text=re.sub(r'^```(?:json)?\s*|\s*```$', '', text, flags=re.S)
    return json.loads(text)

def validate(plan):
    files=plan.get('files',[])
    if not 1 <= len(files) <= 5:
        raise ValueError('Plan must change 1-5 files')
    forbidden=('.github/','.git/','.env')
    for item in files:
        path=item['path'].replace('\\','/')
        if path.startswith(forbidden) or '..' in Path(path).parts:
            raise ValueError(f'Forbidden path: {path}')
        if len(item.get('content','').splitlines()) > 500:
            raise ValueError(f'File too large: {path}')
    branch=plan.get('branch','')
    if not re.fullmatch(r'ai/[a-z0-9][a-z0-9._-]{2,60}', branch):
        raise ValueError('Branch must match ai/<slug>')

def apply(plan):
    sh('git','checkout','-b',plan['branch'])
    for item in plan['files']:
        p=Path(item['path']); p.parent.mkdir(parents=True,exist_ok=True)
        p.write_text(item['content'])
    sh('git','add','--',*[x['path'] for x in plan['files']])
    if not sh('git','status','--porcelain'):
        raise ValueError('No changes produced')
    subprocess.run(['git','diff','--cached','--check'],check=True)
    sh('git','commit','-m',plan['commit_message'])
    sh('git','push','--set-upstream','origin',plan['branch'])
    pr_body=plan['pr_body']+'\n\nGenerated by NVIDIA NIM automation. Repository-scoped test agent.'
    sh('gh','pr','create','--base','main','--head',plan['branch'],'--title',plan['pr_title'],'--body',pr_body)

if __name__ == '__main__':
    actual=os.getenv('GITHUB_REPOSITORY','')
    if actual != ALLOWED_REPO:
        raise SystemExit(f'Repository blocked: {actual!r}')
    prompt="Review this repository snapshot and make one small useful change.\n"+repo_context()
    plan=call_nim(prompt)
    validate(plan)
    print(json.dumps(plan,indent=2))
    apply(plan)
